# Generated by Django 5.1.6 on 2025-02-25 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_company_jobdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_logo',
            new_name='logo',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_location',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_name',
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('skills', models.TextField(help_text='Comma-separated list of skills.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.company')),
            ],
        ),
        migrations.DeleteModel(
            name='JobDetail',
        ),
    ]
