# Generated by Django 5.1.6 on 2025-02-25 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_rename_company_email_company_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
